### ISSUE TITLE
Update ...

### ISSUE THREAD

**Issue by mrtargaryen** [adeweever91/searx_ss#1]
Hey ...

I love this version with the SSL cert

I'm just wondering if you'll be updating it any time soon. I ask as I've noticed some changes over at searx.me

Thanks for a great version of searx its great for use in my LAN.

I use it with Docker and it runs perfectly.

**Comment by adeweever91** [comment]
Glad it works well!

I just updated the image on Docker hub as well as updated the readme so you can rebuild when new versions come out.

**Comment by mrtargaryen** [comment]
Awesom, thanks.

If I had the technical know how I'd do it myself but I'm not so great with remembering command  dline code etc.

I'm trying to get my family and find interested in your version. It really is much better than using Google alone.

Thanks again,

Simon
