### ISSUE TITLE
Morty - Proxy for Searx

### ISSUE THREAD

**Issue by mrtargaryen** [adeweever91/searx_ss#2]
Hey,

I'm just wondering if you know how to add Morty [https://github.com/asciimoo/morty](url) in Docker SearX. I'm very limited in my understanding of things like this (I couldn't find Morty on the Docker Store). If you are unaware about how to achieve this that's OK. 

Thanks.

**Comment by adeweever91** [comment]
I took a quick look, do you know how to be sure its working? I think I have it setup but it doesnt look like Morty is logging anything and searx isnt logging anything about Morty either.

**Comment by mrtargaryen** [comment]
Hey, thanks for the reply.

At searx.me you'll see a proxy option for each search result thats the only way I can determine if its working. I tried setting up Morty myself but had no luck. It appears to be difficult to get it working, and I lack the technical skills to diagnose any issues. Hopefully that will change as I keep studying at university lol :-)

Encrypted email sent from Protonmail in Switzerland

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by adeweever91** [comment]
Oh nevermind, I see (proxied, under the result). It is working. Ill try to push a new docker image tomorrow.

**Comment by mrtargaryen** [comment]
Awesome, I look forward to testing it out. I'll also share it on Reddit, I think there will be a few in the various privacy related sub Reddits who'll be interested in it.

Thanks again :-)

**Comment by adeweever91** [comment]
I pushed an update to the repo and a new image to docker hub that kind of works. Theres still some issues with viewing proxied pages(you can do it but is limited, for example search for "Rick and Morty" and look at the wikipedia page differences between your self hosted instance and searx.me), but the results are proxied correctly. Ill try and dig more into.

**Comment by adeweever91** [comment]
Make sure you set the base url as https://IP or https://example.com otherwise it wont work correctly.

**Comment by mrtargaryen** [comment]
Awesome, cheers.

Thank you for taking the time out to do this, I really appreciate it.

**Comment by mrtargaryen** [comment]
Hey,

Sorry to bother you again (I really do appreciate your help).

I deleted last versy of adeweever91/searx_ss

And the in CLI I ran:

docker run -d -p 80:80 -p 443:443 -e BASE_URL="localhost" -e IMAGE_PROXY="True" adeweever91/searx_ss

(I only run it on my localhost behind a VPN)

And when it starts the container stops within 5-10 seconds. I can't get it to start properly. And I don't know the procedure to diagnose and solve the issue.

If you are too busy at the moment, I understand. Get back to me when you have time.

Thanks :-)

**Comment by adeweever91** [comment]
I just updated the readme I forgot to add the Morty Key var. also make sure to set the base url to https://localhost 
You should not need to pull a new image.

**Comment by mrtargaryen** [comment]
Thanks for the reply,

I completely uninstalled docker and cleaned out any leftovers. Then re-installed and used Kitematic to install adeweever91/searx_ss and this is what was returned;

Generating a 4096 bit RSA private key
..................................................................................................................................................................................................................................................................................................................................++
................................++
writing new private key to '/usr/local/searx/ssl/searx.key'
-----
Error: Format string '/root/go/bin/morty -key %(ENV_MORTY_KEY)s -listen 127.0.0.1:3000' for 'program:morty.command' contains names ('ENV_MORTY_KEY') which cannot be expanded. Available names: ENV_HOME, ENV_HOSTNAME, ENV_PATH, ENV_PWD, ENV_SHLVL, ENV_TERM, group_name, here, host_node_name, process_num, program_name in section 'program:morty' (file: '/etc/supervisord.conf')
For help, use /usr/bin/supervisord -h

I'm not qualified enough to know what all of that means.

Encrypted email sent from Protonmail in Switzerland

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by adeweever91** [comment]
look at the readme. you need to make sure you have the right env vars. your missing MORTY_KEY. i would recommend using the docker-compose file and not docker run. https://docs.docker.com/compose/overview/

**Comment by mrtargaryen** [comment]
I'm not sure what I did, but its now working, the proxy is blocking all javascript and basically just displaying sites in markdown. However, on some sites I receive the error message:

"MortyProxy
Error: timeout
Warning! This instance does not support direct URL opening."

Thank you for taking the time out to do this, I really appreciate it. :-)

Encrypted email sent from Protonmail in Switzerland

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by adeweever91** [comment]
does searx.me not strip javascript?

**Comment by mrtargaryen** [comment]
Thank you. And especially thank you for your patients as I learn all about docker and github.

Simon

Encrypted email sent from Protonmail in Switzerland

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
